owner: klutzybubbles
repo: alchemy-unbound-status

sites:
  - name: Alchemy Unbound API
    url: $API_URL?token=$API_TOKEN
  - name: Steam API
    url: $STEAM_URL?key=$STEAM_TOKEN&appid=2858840

status-website:
  cname: status.alchemyunbound.net
  themeUrl: https://raw.githubusercontent.com/KlutzyBubbles/alchemy-unbound-status/master/assets/theme.css
  logoUrl: https://raw.githubusercontent.com/KlutzyBubbles/alchemy-unbound-status/master/assets/512x512.png
  name: Alchemy Unbound Status
  introMessage: Ideally it should not go down, but this is here to make sure you are not crazy if you are having issues. Status is checked every 10 minutes.
  navbar:
    - title: Steam Store
      href: https://store.steampowered.com/app/2858840/Alchemy_Unbound/
    - title: GitHub
      href: https://github.com/$OWNER/alchemy-unbound
workflowSchedule:
  uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
