owner: klutzybubbles
repo: alchemy-unbound-status

sites:
  - name: Alchemy Unbound API
    url: $API_URL?token=$API_TOKEN
    icon: https://status.alchemyunbound.net/api_icon.png
    maxResponseTime: 1000
    assignees:
      - KlutzyBubbles
  - name: Steam API
    url: $STEAM_URL?key=$STEAM_TOKEN&appid=2858840
    icon: https://status.alchemyunbound.net/steam_icon.png
    maxResponseTime: 1000
  - name: OpenAI API
    url: $OPENAI_URL
    headers:
      - "Authorization: Bearer $OPENAI_TOKEN"
    icon: https://status.alchemyunbound.net/openai_icon.png
    maxResponseTime: 2000

status-website:
  cname: status.alchemyunbound.net
  themeUrl: https://status.alchemyunbound.net/theme.css
  logoUrl: https://status.alchemyunbound.net/api_icon.png
  name: Alchemy Unbound Status
  introMessage: Ideally it should not go down, but this is here to make sure you are not crazy if you are having issues. Steam and OpenAI API status also include any rate limited issues, which means their API could be working but my connection isnt working. Status is checked every 10 minutes.
  navbar:
    - title: Steam Store
      href: https://store.steampowered.com/app/2858840/Alchemy_Unbound/
    - title: GitHub
      href: https://github.com/$OWNER/alchemy-unbound
workflowSchedule:
  uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
